// <auto-generated />
namespace DOGAN.AmbarStokTakip.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AmbarStokTakip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AmbarStokTakip));
        
        string IMigrationMetadata.Id
        {
            get { return "202206291355380_AmbarStokTakip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
